#include <verilated.h> // Verilator's core runtime library

#include "../Inc/UartDriver.h"
#include "Vuart.h"     // This will be generated by Verilator during the CMake build

UartDriver::UartDriver() : m_core(std::make_unique<Vuart>()), m_time(0) 
{
    reset();
}

UartDriver::~UartDriver() 
{
    // Required by Verilator to safely dump any final simulation coverage or wave data
    m_core->final(); 
}

void UartDriver::reset() 
{
    m_core->rst = 1;
    tickClock(5); // Hold the reset pin high for 5 clock cycles
    m_core->rst = 0;
}

void UartDriver::tickClock(uint64_t cycles) 
{
    for (uint64_t i = 0; i < cycles; ++i) 
    {
        // Drop clock low and evaluate logic
        m_core->clk = 0;
        m_core->eval();

        // Raise clock high and evaluate logic (this triggers always_ff blocks)
        m_core->clk = 1;
        m_core->eval();
        
        m_time++;
    }
}

void UartDriver::setRxPin(bool state) 
{
    m_core->rx = state;
}

bool UartDriver::readTxPin() const 
{
    return m_core->tx;
}